name: Setup Java
description: Setup Java SDK
author: Incognia
inputs:
  java-version:
    description: "The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in actions/setup-java's README"
    required: true
  distribution:
    description: "Java distribution. See the list of supported distributions in actions/setup-java's README"
    default: 'adopt'
runs:
  using: composite
  steps:
  - name: Setup Java proper
    uses: actions/setup-java@v2
    with:
      java-version: ${{ inputs.java-version }}
      distribution: ${{ inputs.distribution }}

  - name: Disable Gradle daemon and setup console output
    shell: bash
    run: |
      echo "GRADLE_OPTS=-Dorg.gradle.daemon=false -Dorg.gradle.console=plain $GRADLE_OPTS" >> $GITHUB_ENV
