name: Setup Java
description: Setup Java SDK
author: Incognia
inputs:
  java-version:
    description: "The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in actions/setup-java's README"
    required: true
  distribution:
    description: "Java distribution. See the list of supported distributions in actions/setup-java's README"
    default: 'adopt'
runs:
  using: composite
  steps:
  - name: Setup Java proper
    uses: actions/setup-java@v2
    with:
      java-version: ${{ inputs.java-version }}
      distribution: ${{ inputs.distribution }}

  - name: Disable Gradle daemon and setup console output
    shell: bash
    run: |
      mkdir -p ~/.gradle
      cat <<EOF >> ~/.gradle/gradle.properties
        org.gradle.caching=true
        org.gradle.configureondemand=true
        org.gradle.console=plain
      EOF

  - name: Get AWS credentials for build cache
    uses: inloco/actions-configure-aws-credentials@HEAD
    id: aws-credentials
    with:
      aws-region: ${{ env.AWS_REGION }}
      role-to-assume: arn:aws:iam::779099367007:role/github-actions-storage

  - name: Setup S3-based build cache
    shell: bash
    run: |
      mkdir -p ~/.gradle/init.d
      cat <<EOF >> ~/.gradle/init.d/build-cache.gradle
        initscript {
            repositories {
                maven {
                  url "https://plugins.gradle.org/m2/"
                }
            }
            dependencies {
                classpath "com.github.burrunan.s3cache:s3-build-cache:1.3"
            }
        }

        import com.github.burrunan.s3cache.AwsS3Plugin

        gradle.settingsEvaluated { settings ->
            new AwsS3Plugin().apply(settings)
            settings.buildCache {
                remote(com.github.burrunan.s3cache.AwsS3BuildCache) {
                    awsAccessKeyId = '${{ steps.aws-credentials.outputs.aws-access-key-id }}'
                    awsSecretKey = '${{ steps.aws-credentials.outputs.aws-secret-access-key }}'
                    sessionToken = '${{ steps.aws-credentials.outputs.aws-session-token }}'
                    region = '${{ env.AWS_REGION }}'
                    bucket = 'incognia-github-actions-storage'
                    prefix = 'build-cache/${{ github.repository }}/'
                    push = true
                }
            }
        }
      EOF
